"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\annotation\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\io\abstracts\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\io\base\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\io\digest\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\io\interfaces\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\io\os\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\io\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\lang\abstracts\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\lang\impl\sequences\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\lang\reflect\optdeclared\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\lang\reflect\safety\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\lang\reflect\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\lang\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\net\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\statics\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\time\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\util\encode\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\util\interfaces\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\util\json\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\util\thread\*.java
"C:\Program Files\Java\jdk1.8.0_212\bin\javac" -parameters -encoding UTF-8  -d classes -sourcepath src src\top\fols\box\util\*.java
echo Comilper Complete
